### ISSUE TITLE
Python3 ssh_brute error

### ISSUE THREAD

**Issue by Ali-Razmjoo** [viraintel/OWASP-Nettacker#33]
Hello,

There is a bug in the `ssh_brute` module. I glad if anyone could help!

```
$ python3 nettacker.py -i 127.0.0.1 -m ssh_brute



   ______          __      _____ _____
  / __ \ \        / /\    / ____|  __ \
 | |  | \ \  /\  / /  \  | (___ | |__) |
 | |  | |\ \/  \/ / /\ \  \___ \|  ___/
 | |__| | \  /\  / ____ \ ____) | |     Version 0.0.1
  \____/   \/  \/_/    \_\_____/|_|     SAME
                          _   _      _   _             _
                         | \ | |    | | | |           | |
  github.com/viraintel   |  \| | ___| |_| |_ __ _  ___| | _____ _ __
  owasp.org              | . ` |/ _ \ __| __/ _` |/ __| |/ / _ \ '__|
  viraintel.com          | |\  |  __/ |_| || (_| | (__|   <  __/ |
                         |_| \_|\___|\__|\__\__,_|\___|_|\_\___|_|



[+] Nettacker engine started ...


[!] you are not using the last version of OWASP Nettacker, please update.
[+] 12 modules loaded ...
[+] target 127.0.0.1 submitted!
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/mnt/c/Users/Zombie/Documents/GitHub/OWASP-Nettacker/lib/brute/ssh/engine.py", line 116, in __connect_to_port
    ssh.connect(target, username='', password='', timeout=timeout_sec, port=port)
  File "/usr/local/lib/python3.5/dist-packages/paramiko/client.py", line 424, in connect
    passphrase,
  File "/usr/local/lib/python3.5/dist-packages/paramiko/client.py", line 714, in _auth
    raise saved_exception
  File "/usr/local/lib/python3.5/dist-packages/paramiko/client.py", line 701, in _auth
    self._transport.auth_password(username, password)
  File "/usr/local/lib/python3.5/dist-packages/paramiko/transport.py", line 1381, in auth_password
    return self.auth_handler.wait_for_response(my_event)
  File "/usr/local/lib/python3.5/dist-packages/paramiko/auth_handler.py", line 226, in wait_for_response
    raise e
paramiko.ssh_exception.AuthenticationException: Authentication failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/mnt/c/Users/Zombie/Documents/GitHub/OWASP-Nettacker/lib/brute/ssh/engine.py", line 122, in __connect_to_port
    if 'Authentication failed.' in ssherr:
TypeError: argument of type 'AuthenticationException' is not iterable
```

Regards.

**Comment by Ali-Razmjoo** [comment]
Hello,

it seems change error to `str` type fixed the problem.

Regards
